<?php

namespace KEURGUI\immoBundle\Repository;

/**
 * CHERCHERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CHERCHERepository extends \Doctrine\ORM\EntityRepository
{
}
