<?php

namespace KEURGUI\immoBundle\Repository;

/**
 * connectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class connectsRepository extends \Doctrine\ORM\EntityRepository
{
}
