<?php

namespace KEURGUI\immoBundle\Repository;

/**
 * reservationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function fr()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $u = $qb->select('r', 'c', 'b')
        ->from('KEURGUIimmoBundle:reservation', 'r')
        ->leftJoin('r.client', 'c')
        ->leftJoin('r.bien', 'b')
        ->where('r.etat = 0')
        ->getQuery();

        return $u->getResult();
    }
}
