<?php

namespace KEURGUI\immoBundle\Repository;

/**
 * typebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typebienRepository extends \Doctrine\ORM\EntityRepository
{
}
